use_frameworks!

platform :ios, '10.0'

target 'UIComponentWithNavigation_Example' do
  pod 'UIComponentWithNavigation', :path => '../'

  target 'UIComponentWithNavigation_Tests' do
    inherit! :search_paths

    
  end
end
